"""Data models used by the editing subsystem in EdgeMind V2."""

from dataclasses import dataclass
from typing import Optional


@dataclass
class EditRequest:
    """Represent a request to prepare a source-code edit."""

    file_path: str
    instruction: str
    source_code: str = ""
    model: str = "qwen2.5-coder:3b"
    source_language: str = "python"
    target_language: str = "python"
    output_file: Optional[str] = None
    preserve_formatting: bool = True
    create_backup: bool = True
    validate_output: bool = True
    generate_diff: bool = True
    metadata: Optional[dict] = None
    source_file: Optional[str] = None
    target_file: Optional[str] = None
    operation: str = "modify"  # "modify" or "create"
    analysis_result: Optional[str] = None  # findings from prior analyze/search steps
    project_path: str = "."


@dataclass
class EditResponse:
    """Represent the preview generated by an editing request."""

    success: bool
    file_path: str
    original_code: str
    modified_code: str
    diff: str
    validation_message: str
    backup_path: Optional[str]
    error: Optional[str]
    operation: str = "modify"
    output_file: Optional[str] = None
    source_file: Optional[str] = None
