from typing import TypedDict


class EdgeMindState(TypedDict):
    # Original user request
    user_query: str

    # Ordered list of tasks generated by the planner
    plan: list[str]

    # Index of the task currently being executed
    current_step: int

    # Current task being processed
    current_task: str

    # Model selected by the router
    selected_model: str

    # Optional file path used by explain/debug tools
    file_path: str

    # Result returned by the executed tool
    result: str

    # Whether the execution evaluator marked this step as successful
    execution_success: bool